### ISSUE TITLE
Octavia のLB機能を試す

### ISSUE THREAD

**Issue by oomichi** [oomichi/try-kubernetes#93]
https://github.com/oomichi/try-kubernetes/issues/68 で構築ができたので、Octavia による LB機能を試す。

**Comment by oomichi** [comment]
LBインスタンスは作成できた。
```
$ openstack loadbalancer create --name lb1 --vip-subnet-id 43ed897b-3c10-4d5c-8f6d-263edcd817c7
$ openstack loadbalancer list
+--------------------------------------+------+----------------------------------+---------------+---------------------+----------+
| id                                   | name | project_id                       | vip_address   | provisioning_status | provider |
+--------------------------------------+------+----------------------------------+---------------+---------------------+----------+
| 3598102c-f4ee-4a0d-971a-e0f30a5c3108 | lb1  | 682e74f275fe427abd9eb6759f3b68c5 | 192.168.1.102 | ACTIVE              | octavia  |
+--------------------------------------+------+----------------------------------+---------------+---------------------+----------+
```
これにBackendに存在すべきVMもしくはコンテナを接続していく。
Octavia の操作方法は https://docs.openstack.org/python-octaviaclient/pike/usage/osc/v2/load-balancer.html
ひとまずリストする
→ `openstack loadbalancer` コマンドではなさそう
- loadbalancer list
- loadbalancer show
- loadbalancer create
- loadbalancer set: enable/disable の設定
- loadbalancer delete

**Comment by oomichi** [comment]
エラー発生中
```
$ openstack loadbalancer pool list
Unable to establish connection to http://iaas-ctrl:9876/v2.0/lbaas/pools: HTTPConnectionPool(host='iaas-ctrl', port=9876): Max retries exceeded with url: /v2.0/lbaas/pools (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f99bb48e550>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

**Comment by oomichi** [comment]
作成済みの LB の詳細を確認したところ、pools は空の状態
```
$ openstack loadbalancer show 3598102c-f4ee-4a0d-971a-e0f30a5c3108
+---------------------+--------------------------------------+
| Field               | Value                                |
+---------------------+--------------------------------------+
| admin_state_up      | True                                 |
| created_at          | 2019-09-06T23:36:05                  |
| description         |                                      |
| flavor              |                                      |
| id                  | 3598102c-f4ee-4a0d-971a-e0f30a5c3108 |
| listeners           |                                      |
| name                | lb1                                  |
| operating_status    | OFFLINE                              |
| pools               |                                      |
| project_id          | 682e74f275fe427abd9eb6759f3b68c5     |
| provider            | octavia                              |
| provisioning_status | ACTIVE                               |
| updated_at          | 2019-09-06T23:38:13                  |
| vip_address         | 192.168.1.102                        |
| vip_network_id      | bfd9fd43-c9b4-43ad-bb67-930c674f2605 |
| vip_port_id         | b43eecf3-e174-442d-8ed5-5e0cc199c994 |
| vip_qos_policy_id   |                                      |
| vip_subnet_id       | 43ed897b-3c10-4d5c-8f6d-263edcd817c7 |
+---------------------+--------------------------------------+
```

**Comment by oomichi** [comment]
Pool の作成
-------------

`openstack loadbalancer create` コマンドで LB の作成は出来たが、そこへ負荷分散先の VM を追加するには Pool 作成、Member登録が必要。まずはPool作成を試してみる。

**Comment by oomichi** [comment]
cpu02, cpu03 への VMスケジューリング失敗
nova-conductor のログ
```
2019-09-09 16:12:29.470 3250 ERROR nova.scheduler.utils [req-16637ca4-a94a-412a-9e88-6053392020f5 e5e99065fd524f328c2f81e28a6fbc42 682e74f275fe427abd9eb6759f3b68c5 - default default] [instance: 602277ba-9dd7-43db-b348-5539374cd655] Error from last host: iaas-cpu02 (node iaas-cpu02): [
u'Traceback (most recent call last):\n
', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 1840, in _do_build_and_run_instance\n
    filter_properties, request_spec)\n
', u'  File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 2117, in _build_and_run_instance\n
    instance_uuid=instance.uuid, reason=six.text_type(e))\n
', u'RescheduledException: Build of instance 602277ba-9dd7-43db-b348-5539374cd655 was re-scheduled: Binding failed for port 47d00d9e-1b92-41a0-98f9-6639fda17538, please check neutron logs for more information.\n']
```

**Comment by oomichi** [comment]
backend サーバに nginx を設定
```
$  sudo apt-get update
$  sudo apt-get install nginx
$  sudo service nginx start
$ sudo netstat -anp | grep nginx
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      12892/nginx: master
tcp6       0      0 :::80                   :::*                    LISTEN      12892/nginx: master
unix  3      [ ]         STREAM     CONNECTED     34290    12892/nginx: master
unix  3      [ ]         STREAM     CONNECTED     34291    12892/nginx: master
$
$ curl http://localhost
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by oomichi** [comment]
Octavia のドキュメントを読むと、一般的に以下の手順で標準的な HTTP LB を作るみたい。

source/user/guides/basic-cookbook.rst

1. Create a LB on public subnet
2. Create a listener
3. Create pool for the above listener
4. Add members of private network to the pool

backend01(192.168.1.117) を Member として追加する。
```
$ openstack loadbalancer listener create --name listener1 --protocol HTTP --protocol-port 80 lb1
$ openstack loadbalancer pool create --name pool1 --lb-algorithm ROUND_ROBIN --listener listener1 --protocol HTTP
$ openstack loadbalancer member create --subnet-id provider --address 192.168.1.117 --protocol-port 80 pool1
$ openstack loadbalancer member list pool1
+--------------------------------------+------+----------------------------------+---------------------+---------------+---------------+------------------+--------+
| id                                   | name | project_id                       | provisioning_status | address       | protocol_port | operating_status | weight |
+--------------------------------------+------+----------------------------------+---------------------+---------------+---------------+------------------+--------+
| 866fd85a-3574-46f6-b667-a1487f28e1d3 |      | 682e74f275fe427abd9eb6759f3b68c5 | ACTIVE              | 192.168.1.117 |            80 | NO_MONITOR       |      1 |
+--------------------------------------+------+----------------------------------+---------------------+---------------+---------------+------------------+--------+
```

**Comment by oomichi** [comment]
iaas-ctrl から LB に対し Curl が通らない。
Octavia、backend01 の Security Group を確認する。
-> TCP/443 (https) しか通らないようになっていた。専用の Security Group を作って試してみる。
```
$ openstack security group create allow-http-https-icmp
$ openstack security group rule create allow-http-https-icmp --protocol tcp --dst-port 22:22 --remote-ip 0.0.0.0/0
$ openstack security group rule create allow-http-https-icmp --protocol icmp
$ openstack security group rule create allow-http-https-icmp --protocol tcp --dst-port 80:80 --remote-ip 0.0.0.0/0
$ openstack security group rule create allow-http-https-icmp --protocol tcp --dst-port 443:443 --remote-ip 0.0.0.0/0
```
作成した security group を指定して VM 作成
```
$ nova boot --key-name mykey --flavor m1.small --image fc29755b-4468-4951-b7e3-0278b0fb3682 --nic net-name=provider --security-groups allow-http-https-icmp backend01
```
