### ISSUE TITLE
Octavia: Could not connect to instance. Retrying.: requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.0.72', port=9443): 

### ISSUE THREAD

**Issue by oomichi** [oomichi/try-kubernetes#98]
以下のように octavia-worker で amphorae インスタンスの設定でエラーが発生、LB 作成に失敗している。
```
2019-09-24 20:51:30.662 2916 WARNING octavia.amphorae.drivers.haproxy.rest_api_driver
   [-] Could not connect to instance. Retrying.: requests.exceptions.ConnectionError:
   HTTPSConnectionPool(host='192.168.0.72', port=9443):
   Max retries exceeded with url: /0.5/info (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f686403a940>: Failed to establish a new connection: [Errno 113] No route to host',))
2019-09-24 20:54:03.460 2916 WARNING octavia.amphorae.drivers.haproxy.rest_api_driver
   [-] Could not connect to instance. Retrying.: requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.0.72', port=9443): 
   Max retries exceeded with url: /0.5/info (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

**Comment by oomichi** [comment]
エラーの内容から、amphorae インスタンスの /0.5/info に対する HTTPS 接続が CERTIFICATE_VERIFY_FAILED で失敗している。
HTTPS 鍵関連の設定がミスってみるように見えるため、設定を見直す。
設定項目は `[haproxy_amphora]` セクションの client_cert と server_ca
最新 Devstack ではこの設定方法に変更が入っている。

**Comment by oomichi** [comment]
ca_certificate の項目が設定されていなかったので、上記で修正。試してみる。
→ 少し進んだ。

しかし、引き続き以下のエラーが発生
```
2019-09-24 22:58:36.676 9196 WARNING octavia.controller.worker.controller_worker [-] Task 'reload-lb-before-allocate-vip' (c7e512ee-3011-470e-be99-73786904a355) transitioned into state 'REVERTED' from state 'REVERTING' with result 'None'
2019-09-24 22:58:36.677 9196 DEBUG octavia.controller.worker.controller_worker [-] Task 'octavia.controller.worker.tasks.lifecycle_tasks.LoadBalancerIDToErrorOnRevertTask' (1e8d1e66-b7cc-4215-8a22-a68634e96339) transitioned into state 'REVERTING' from state 'SUCCESS' _task_receiver /usr/lib/python3/dist-packages/taskflow/listeners/logging.py:194
2019-09-24 22:58:36.726 9196 WARNING octavia.controller.worker.controller_worker [-] Task 'octavia.controller.worker.tasks.lifecycle_tasks.LoadBalancerIDToErrorOnRevertTask' (1e8d1e66-b7cc-4215-8a22-a68634e96339) transitioned into state 'REVERTED' from state 'REVERTING' with result 'None'
2019-09-24 22:58:36.729 9196 WARNING octavia.controller.worker.controller_worker [-] Flow 'octavia-create-loadbalancer-flow' (cac27ea7-d400-4ad7-a0cc-9634f0cd2260) transitioned into state 'REVERTED' from state 'RUNNING'
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server [-] Exception during message handling: octavia.amphorae.drivers.haproxy.exceptions.NotFound: Not Found
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/oslo_messaging/rpc/server.py", line 166, in _process_incoming
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/oslo_messaging/rpc/dispatcher.py", line 265, in dispatch
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/oslo_messaging/rpc/dispatcher.py", line 194, in _do_dispatch
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/octavia/controller/queue/endpoint.py", line 45, in create_load_balancer
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     self.worker.create_load_balancer(load_balancer_id, flavor)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/tenacity/__init__.py", line 292, in wrapped_f
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     return self.call(f, *args, **kw)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/tenacity/__init__.py", line 358, in call
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     do = self.iter(retry_state=retry_state)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/tenacity/__init__.py", line 319, in iter
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     return fut.result()
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     return self.__get_result()
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     raise self._exception
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/tenacity/__init__.py", line 361, in call
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     result = fn(*args, **kwargs)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/octavia/controller/worker/controller_worker.py", line 343, in create_load_balancer
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     create_lb_tf.run()
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/taskflow/engines/action_engine/engine.py", line 247, in run
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     for _state in self.run_iter(timeout=timeout):
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/taskflow/engines/action_engine/engine.py", line 340, in run_iter
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     failure.Failure.reraise_if_any(er_failures)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/taskflow/types/failure.py", line 339, in reraise_if_any
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     failures[0].reraise()
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/taskflow/types/failure.py", line 346, in reraise
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     six.reraise(*self._exc_info)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     raise value
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/taskflow/engines/action_engine/executor.py", line 53, in _execute_task
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     result = task.execute(**arguments)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/octavia/controller/worker/tasks/amphora_driver_tasks.py", line 370, in execute
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     amp_info = self.amphora_driver.get_info(amphora)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/octavia/amphorae/drivers/haproxy/rest_api_driver.py", line 210, in get_info
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     return self.client.get_info(amphora)
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/octavia/amphorae/drivers/haproxy/rest_api_driver.py", line 573, in get_info
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     if exc.check_exception(r):
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server   File "/usr/lib/python3/dist-packages/octavia/amphorae/drivers/haproxy/exceptions.py", line 43, in check_exception
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server     raise responses[status_code]()
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server octavia.amphorae.drivers.haproxy.exceptions.NotFound: Not Found
2019-09-24 22:58:36.729 9196 ERROR oslo_messaging.rpc.server
```

**Comment by oomichi** [comment]
その前にエラーが発生していた。
```
2019-09-24 22:58:24.506 9196 DEBUG octavia.controller.worker.controller_worker [-] Task 'STANDALONE-octavia-create-amp-for-lb-subflow-octavia-amp-compute-connectivity-wait' (a106fb81-a8b8-4a7d-be28-ba0443a5a2fc) transitioned into state 'RUNNING' from state 'PENDING' _task_receiver /usr/lib/python3/dist-packages/taskflow/listeners/logging.py:194
2019-09-24 22:58:24.507 9196 DEBUG octavia.amphorae.drivers.haproxy.rest_api_driver [-] request url info request /usr/lib/python3/dist-packages/octavia/amphorae/drivers/haproxy/rest_api_driver.py:462
2019-09-24 22:58:24.508 9196 DEBUG octavia.amphorae.drivers.haproxy.rest_api_driver [-] request url https://192.168.0.22:9443/0.5/info request /usr/lib/python3/dist-packages/octavia/amphorae/drivers/haproxy/rest_api_driver.py:465
2019-09-24 22:58:31.742 9196 DEBUG octavia.amphorae.drivers.haproxy.rest_api_driver [-] Connected to amphora. Response: <Response [404]> request /usr/lib/python3/dist-packages/octavia/amphorae/drivers/haproxy/rest_api_driver.py:486
2019-09-24 22:58:31.743 9196 DEBUG octavia.amphorae.drivers.haproxy.rest_api_driver [-] Got a 404 (content-type: application/json) -- connection data: b'{"error":"404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.","http_code":404}' request /usr/lib/python3/dist-packages/octavia/amphorae/drivers/haproxy/rest_api_driver.py:496
2019-09-24 22:58:31.744 9196 ERROR octavia.amphorae.drivers.haproxy.exceptions [-] Amphora agent returned unexpected result code 404 with response {'error': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'http_code': 404}
2019-09-24 22:58:31.776 9196 WARNING octavia.controller.worker.controller_worker [-] Task 'STANDALONE-octavia-create-amp-for-lb-subflow-octavia-amp-compute-connectivity-wait' (a106fb81-a8b8-4a7d-be28-ba0443a5a2fc) transitioned into state 'FAILURE' from state 'RUNNING'
```
これは、前回 HTTPS 接続エラーだった https://192.168.0.22:9443/0.5/info への接続が NotFound(404) でエラーになったことが原因。

**Comment by oomichi** [comment]
なぜ、上記でうまくいかないのか不明。
そもそも、Polling 元はどこで Version を指定してる？
octavia/amphorae/drivers/haproxy/rest_api_driver.py
そもそも新旧バージョンのクライアントが用意されているように見える。
設定ファイルでの切替え方法は？
```
673 class AmphoraAPIClient0_5(AmphoraAPIClientBase):
674     def __init__(self):
675         super(AmphoraAPIClient0_5, self).__init__()
...
789 class AmphoraAPIClient1_0(AmphoraAPIClientBase):
790     def __init__(self):
791         super(AmphoraAPIClient1_0, self).__init__()
```

**Comment by oomichi** [comment]
stable/rocky をチェックアウトしてみた。
イメージ作成はうまくいくが、 `https://192.168.0.80:9443/0.5/info` への接続が timeout している。

**Comment by oomichi** [comment]
amphora が v1.0 に変更された stable/stein をベースにした Octavia の Ubuntu パッケージがリリースされた後、バージョンアップして試すことにすることにした。
cloud-provider-openstack の Issue にも登録済み。

**Comment by oomichi** [comment]
4.0.0 (Stein) の Tag でチェックアウトしてビルドしたところ、ビルドは成功した。
しかし、引き続き timeout している。
そもそも `/0.5/info` のエンドポイントが存在しない場合は NotFound (404) のはずなのにその前段である timeout が発生しているということは別の問題に直面している可能性が高い。
security group の見直しは完了
 -> 問題なし：944もん3/TCP が security group で許可され、その security group が octavia.conf で指定されていることを確認済み

**Comment by oomichi** [comment]
その前に Neutron 関連のログが Octavia 側で出ていた。
```
2019-09-25 23:05:10.462 9196 DEBUG octavia.controller.worker.tasks.network_tasks [-] Deallocating a VIP 192.168.1.196 execute /usr/lib/python3/dist-packages/octavia/controller/worker/tasks/
network_tasks.py:457
2019-09-25 23:05:10.590 9196 DEBUG octavia.network.drivers.neutron.base [-] Neutron extension security-group found enabled _check_extension_enabled /usr/lib/python3/dist-packages/octavia/ne
twork/drivers/neutron/base.py:66
2019-09-25 23:05:10.719 9196 DEBUG neutronclient.v2_0.client [-] Error message: {"message": "The resource could not be found.<br /><br />\nExtension with alias dns-integration does not exis
t\n\n", "code": "404 Not Found", "title": "Not Found"} _handle_fault_response /usr/lib/python3/dist-packages/neutronclient/v2_0/client.py:259
2019-09-25 23:05:10.719 9196 DEBUG octavia.network.drivers.neutron.base [-] Neutron extension dns-integration is not enabled _check_extension_enabled /usr/lib/python3/dist-packages/octavia/
network/drivers/neutron/base.py:70
2019-09-25 23:05:10.849 9196 DEBUG neutronclient.v2_0.client [-] Error message: {"message": "The resource could not be found.<br /><br />\nExtension with alias qos does not exist\n\n", "cod
e": "404 Not Found", "title": "Not Found"} _handle_fault_response /usr/lib/python3/dist-packages/neutronclient/v2_0/client.py:259
2019-09-25 23:05:10.849 9196 DEBUG octavia.network.drivers.neutron.base [-] Neutron extension qos is not enabled _check_extension_enabled /usr/lib/python3/dist-packages/octavia/network/driv
ers/neutron/base.py:70
2019-09-25 23:05:10.976 9196 DEBUG octavia.network.drivers.neutron.base [-] Neutron extension allowed-address-pairs found enabled _check_extension_enabled /usr/lib/python3/dist-packages/oct
avia/network/drivers/neutron/base.py:66
2019-09-25 23:05:11.220 9196 DEBUG neutronclient.v2_0.client [-] Error message: {"NeutronError": {"type": "PortNotFound", "message": "Port 2be79251-b99a-4b3b-b9e8-4397914c9e26 could not be
found.", "detail": ""}} _handle_fault_response /usr/lib/python3/dist-packages/neutronclient/v2_0/client.py:259
2019-09-25 23:05:11.221 9196 WARNING octavia.network.drivers.neutron.allowed_address_pairs [-] Can't deallocate VIP because the vip port 2be79251-b99a-4b3b-b9e8-4397914c9e26 cannot be found
 in neutron. Continuing cleanup.: octavia.network.base.PortNotFound: port not found (port id: 2be79251-b99a-4b3b-b9e8-4397914c9e26).
```
